language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

sudo: false

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

notifications:
  email: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
